<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Main Housing Sections -->

  <xacro:macro name="joints" params="prefix p d">
    <joint name="${prefix}_housing_joint" type="fixed">
      <origin xyz="${d} 0 0" rpy="0 0 0" />
      <parent link="${p}" />
      <child link="${prefix}_housing" />
    </joint>
  </xacro:macro>
  <xacro:joints prefix="fwd" d="${(fwd_length+mid_length)/2}" p="mid_housing" />
  <xacro:joints prefix="mid" d="${(aft_length-fwd_length)/2}" p="base_link" />
  <xacro:joints prefix="aft" d="${-(aft_length+mid_length)/2}" p="mid_housing" />

  <xacro:macro name="links" params="prefix radius length">
    <link name="${prefix}_housing">
      <visual>
        <xacro:insert_block name="cylinder_fix" />
        <geometry>
          <cylinder radius="${radius}" length="${length}" />
        </geometry>
        <material name="FlatBlack" />
      </visual>
    </link>
  </xacro:macro>
  <xacro:links prefix="fwd" radius="${housing_radius}" length="${fwd_length}"/>
  <xacro:links prefix="mid" radius="${middle_radius}" length="${mid_length}"/>
  <xacro:links prefix="aft" radius="${housing_radius}" length="${aft_length}"/>

  <!-- Thruster Mounting Points -->

  <joint name="aft_thruster_mount_joint" type="fixed">
    <origin xyz="${riser_x} 0 ${riser_z-riser_height}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="aft_thruster_mount" />
  </joint>

  <link name="aft_thruster_mount">
    <visual>
      <geometry>
        <cylinder radius="${riser_length/2}" length="${riser_height}" />
      </geometry>
      <material name="FlatBlack" />
    </visual>
  </link>

  <xacro:macro name="thruster_mounts" params="prefix reflect">
    <joint name="${prefix}_thruster_mount_joint" type="fixed">
      <origin xyz="${shaft_x} ${reflect*(shaft_y-shaft_length)} 0" rpy="0 0 0"/>
      <parent link="base_link" />
      <child link="${prefix}_thruster_mount" />
    </joint>
    <link name="${prefix}_thruster_mount">
      <visual>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        <geometry>
          <cylinder radius="${shaft_radius*0.75}" length="${shaft_length}" />
        </geometry>
        <material name="FlatBlack" />
      </visual>
    </link>
  </xacro:macro>
  <xacro:thruster_mounts prefix="port" reflect="1"/>
  <xacro:thruster_mounts prefix="stbd" reflect="-1"/>

  <!-- URDF Materials -->

  <material name="FlatBlack">
    <color rgba="0.1 0.1 0.1 1.0" />
  </material>
  <material name="DarkGrey">
    <color rgba="0.175 0.175 0.175 1.0" />
  </material>
  <material name="Grey">
    <color rgba="0.3 0.3 0.3 1.0" />
  </material>
  <material name="GreyTransparent">
    <color rgba="0.5 0.5 0.5 0.5" />
  </material>
  <material name="Orange">
    <color rgba="1 0.5088 0.0468 1" />
  </material>

</robot>
