<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

<!--                    -->
<!--  Ballast Mounting  -->
<!--                    -->

  <xacro:property name="total" value="4.75"/>
  <xacro:property name="mass" value="${total/2}"/>
  <xacro:property name="length" value="${mass/2700/2/(M_PI*body_radius*body_radius)}"/>
  <xacro:property name="inertia">
    <inertia ixx="${mass*body_radius^2/2}" ixy="0.0" ixz="0.0"
             iyy="${mass/12*(3*body_radius*body_radius+length*length)}" iyz="0.0"
             izz="${mass/12*(3*body_radius*body_radius+length*length)}"/>
  </xacro:property>

  <xacro:macro name="ballast" params="prefix reflect">
    <joint name="${prefix}_ballast_joint" type="fixed">
      <origin xyz="${1.5*body_radius} ${reflect*(housing_radius-body_radius)} -${housing_radius+body_radius}" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="${prefix}_ballast"/>
    </joint>
    <link name="${prefix}_ballast">
      <inertial>
        <mass value="${mass}"/>
        <xacro:insert_block name="inertia"/>
      </inertial>
      <visual>
        <xacro:insert_block name="pitch_fix"/>
        <geometry>
            <cylinder radius="${body_radius}" length="${length}"/>
        </geometry>
        <material name="Grey"/>
      </visual>
      <collision>
        <xacro:insert_block name="pitch_fix"/>
        <geometry>
            <cylinder radius="${body_radius}" length="${length}"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>
  <xacro:ballast prefix="port" reflect="1"/>
  <xacro:ballast prefix="stbd" reflect="-1"/>

<!--                     -->
<!--  Thruster Mounting  -->
<!--                     -->
  <!--    Port & Starboard Servos    -->

  <xacro:macro name="servo" params="prefix reflect mirror">
    <joint name="${prefix}_servo" type="revolute">
      <origin xyz="${shaft_x} ${reflect*shaft_y} 0" rpy="0 ${zero} ${mirror}"/>
      <parent link="housing"/>
      <child link="${prefix}_servo_shaft"/>
      <axis xyz="${servo_axis}"/>
      <limit lower="${min}" upper="${max}" effort="${tau}" velocity="${vel}"/>
    </joint>
    <link name="${prefix}_servo_shaft">
      <inertial>
        <mass value="${shaft_mass}"/>
        <xacro:insert_block name="shaft_inertia"/>
      </inertial>
      <visual>
        <xacro:insert_block name="roll_fix"/>
        <geometry>
          <cylinder radius="${shaft_radius}" length="${shaft_length}"/>
        </geometry>
        <material name="DarkGrey"/>
      </visual>
      <collision>
        <xacro:insert_block name="roll_fix"/>
        <geometry>
          <cylinder radius="${shaft_radius}" length="${shaft_length}"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>
  <xacro:servo prefix="port" reflect="1" mirror="0"/>
  <xacro:servo prefix="stbd" reflect="-1" mirror="${M_PI}"/>

  <!--    Aft Thruster Riser    -->

  <joint name="aft_thruster_riser_joint" type="fixed">
    <origin xyz="${riser_x} 0 ${riser_z}" rpy="0 0 0"/>
    <parent link="housing"/>
    <child link="aft_thruster_riser"/>
  </joint>

  <link name="aft_thruster_riser">
    <inertial>
      <mass value="${riser_mass}"/>
      <xacro:insert_block name="riser_inertia"/>
    </inertial>
    <visual>
      <geometry>
        <box size="${0.75*riser_length} ${0.55*riser_width} ${riser_height}"/>
      </geometry>
      <material name="DarkGrey"/>
    </visual>
    <collision>
      <geometry>
        <box size="${riser_length} ${riser_width} ${riser_height}"/>
      </geometry>
    </collision>
  </link>

  <!--    Port & Stbd Shaft Seals    -->

  <xacro:macro name="thruster_mounts" params="prefix reflect">
    <joint name="${prefix}_thruster_mount_joint" type="fixed">
      <origin xyz="${shaft_x} ${reflect*(shaft_y-shaft_length)} 0" rpy="0 0 0"/>
      <parent link="housing"/>
      <child link="${prefix}_thruster_mount"/>
    </joint>
    <link name="${prefix}_thruster_mount">
      <visual>
        <xacro:insert_block name="roll_fix"/>
        <geometry>
          <cylinder radius="${shaft_radius*0.75}" length="${shaft_length}"/>
        </geometry>
        <material name="FlatBlack"/>
      </visual>
    </link>
  </xacro:macro>
  <xacro:thruster_mounts prefix="port" reflect="1"/>
  <xacro:thruster_mounts prefix="stbd" reflect="-1"/>

  <!--    Aft Thruster Mounting Point    -->

  <joint name="aft_thruster_mount_joint" type="fixed">
    <origin xyz="${riser_x} 0 ${riser_z-riser_height}" rpy="0 0 0"/>
    <parent link="housing"/>
    <child link="aft_thruster_mount"/>
  </joint>

  <link name="aft_thruster_mount">
    <visual>
      <geometry>
        <cylinder radius="${riser_length/2}" length="${riser_height}"/>
      </geometry>
      <material name="FlatBlack"/>
    </visual>
  </link>

</robot>
