<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!--  Main Housing Inertia  -->

  <link name="housing">
    <inertial>
      <mass value="${housing_mass}" />
      <xacro:insert_block name="housing_inertia" />
    </inertial>
  </link>

  <!--  Main Housing Volume  -->

  <xacro:macro name="joints" params="prefix d p">
    <joint name="${prefix}_housing_joint" type="fixed">
      <origin xyz="${d} 0 0" rpy="0 0 0" />
      <parent link="${p}" />
      <child link="${prefix}_housing" />
    </joint>
  </xacro:macro>
  <xacro:joints prefix="fwd" d="${(fwd_length+mid_length)/2}" p="mid_housing" />
  <xacro:joints prefix="mid" d="${(aft_length-fwd_length)/2}" p="housing" />
  <xacro:joints prefix="aft" d="${-(aft_length+mid_length)/2}" p="mid_housing" />

  <xacro:macro name="links" params="prefix radius length">
    <link name="${prefix}_housing">
      <visual>
        <xacro:insert_block name="cylinder_fix" />
        <geometry>
          <cylinder radius="${radius}" length="${length}" />
        </geometry>
        <material name="FlatBlack" />
      </visual>
      <collision>
        <xacro:insert_block name="cylinder_fix" />
        <geometry>
          <cylinder radius="${radius}" length="${length}" />
        </geometry>
      </collision>
    </link>
  </xacro:macro>
  <xacro:links prefix="fwd" radius="${housing_radius}" length="${fwd_length}"/>
  <xacro:links prefix="mid" radius="${middle_radius}" length="${mid_length}"/>
  <xacro:links prefix="aft" radius="${housing_radius}" length="${aft_length}"/>

  <!--  Gaskets  -->

  <xacro:macro name="gasket" params="prefix reflect">
    <joint name="${prefix}_gasket_joint" type="fixed">
      <origin xyz="${reflect*gasket_x} 0 0" rpy="0 0 0" />
      <parent link="housing" />
      <child link="${prefix}_gasket" />
    </joint>
    <link name="${prefix}_gasket">
      <inertial>
        <mass value="${gasket_mass}" />
        <xacro:insert_block name="gasket_inertia" />
      </inertial>
      <visual>
        <xacro:insert_block name="cylinder_fix" />
        <geometry>
          <cylinder radius="${housing_radius}" length="${gasket_length}" />
        </geometry>
        <material name="Orange" />
      </visual>
      <collision>
        <xacro:insert_block name="cylinder_fix" />
        <geometry>
          <cylinder radius="${housing_radius}" length="${gasket_length}" />
        </geometry>
      </collision>
    </link>
  </xacro:macro>
  <xacro:gasket prefix="fwd" reflect="1" />
  <xacro:gasket prefix="aft" reflect="-1" />

  <!--  Dome/Endcap  -->

  <joint name="dome_joint" type="fixed">
    <origin xyz="${gasket_length/2} 0 0" rpy="0 0 0" />
    <parent link="fwd_gasket" />
    <child link="dome" />
  </joint>

  <joint name="endcap_joint" type="fixed">
    <origin xyz="${-(endcap_length+gasket_length)/2} 0 0" rpy="0 0 0" />
    <parent link="aft_gasket" />
    <child link="endcap" />
  </joint>

  <link name="dome">
    <inertial>
      <mass value="${dome_mass}" />
      <xacro:insert_block name="dome_inertia" />
    </inertial>
    <visual>
      <geometry>
        <sphere radius="${housing_radius}" />
        <!-- <mesh filename="package://jaws2_description/meshes/dome.stl" /> -->
      </geometry>
      <material name="Grey" />
    </visual>
    <collision>
      <geometry>
        <sphere radius="${housing_radius}" />
      </geometry>
    </collision>
  </link>

  <link name="endcap">
    <inertial>
      <mass value="${endcap_mass}" />
      <xacro:insert_block name="endcap_inertia" />
    </inertial>
    <visual>
      <xacro:insert_block name="cylinder_fix" />
      <geometry>
        <cylinder radius="${housing_radius}" length="${endcap_length}" />
      </geometry>
      <material name="Grey" />
    </visual>
    <collision>
      <xacro:insert_block name="cylinder_fix" />
      <geometry>
        <cylinder radius="${housing_radius}" length="${endcap_length}" />
      </geometry>
    </collision>
  </link>

</robot>
